### ISSUE TITLE
bug/persistence-saves-state-to-storage-when-it-shouldnt

### ISSUE THREAD

**Issue by imranariffin** [hooligram/hooligram-client#29]
The expression used against action type in persistence middleware is incorrect:

```
if (
  action.type.startsWith('PERSISTENCE:') && (
    !action.type.match(/API:(.*)_SUCCESS/) || 
    !action.type.match(/API:(.*)_FAILURE/)
  )
) {
  // do not save state to storage
  return
}
// save state to storage
```
When:
Action is dispatched that is not an api response 

Expected:
State should not be persisted

Actual:
State is persisted

**Comment by imranariffin** [comment]
@cglotr Wanna pick this one up?

I think it might also be too to add some tests

**Comment by cglotr** [comment]
@imranariffin yeah, I will pick this up. Just need to do some cleaning on the server for a bit. Will pick it up after I finish with the cleanup/refactor.
