### ISSUE TITLE
refactor/migrate-to-react-native-config

### ISSUE THREAD

**Issue by imranariffin** [hooligram/hooligram-client#37]
`react-native-dotenv` has been very buggy in picking up changes in .env file -- it is very annoying to add, for example, a new line just to trigger it to pick up the changes and even then it may not work and even when it does work you cannot remove the added new line or else your changes to .env will be ignored again without you realizing it.

I suggest we migrate to `react-native-config` which I have used at work. Never had a problem with it so far.
link: https://github.com/luggit/react-native-config

**Comment by cglotr** [comment]
@imranariffin Agreed. I also have wasted hours trying to figure out why the client is not hitting the correct server after changing the `.env`. I think I have to restart the emulator to get the `.env` read properly LOL

**Comment by imranariffin** [comment]
[:disappointed:,:angry:,:-1:,:anger:].each(applyOn(`react-native-dotenv`))
