### ISSUE TITLE
Put action types in one place

### ISSUE THREAD

**Issue by cglotr** [hooligram/hooligram-client#39]
I think we should put all the action types in one place. Actions are/should be the only way to change the state of the app. Putting them in one place will make it easy to understand the code base. As of now, they are scattered across the app. If we put all possible action types in one place, it will be easier to draw out the Finite State Machine (FSM) later.

**Comment by cglotr** [comment]
@imranariffin

**Comment by imranariffin** [comment]
Let's do it
