### ISSUE TITLE
inconsistent file naming

### ISSUE THREAD

**Issue by cglotr** [hooligram/hooligram-client#40]
The file names are not consistent and it's not obvious why certain name convention is used. For example `hooligramApi.js` & `persistence-api.js`

**Comment by imranariffin** [comment]
The naming were arbitrary. We should stick to one. Personally I prefer `foo-bar.js` over `fooBar.js` for files other than classes or React components.

**Comment by cglotr** [comment]
> The naming were arbitrary. We should stick to one. Personally I prefer `foo-bar.js` over `fooBar.js` for files other than classes or React components.

Yeah, let's go for `foo-bar.js` convention for other than React stuff
