### ISSUE TITLE
Should we remove form states from the store?

### ISSUE THREAD

**Issue by cglotr** [hooligram/hooligram-client#44]
https://github.com/hooligram/hooligram-client/blob/5c37cca2419791c9d698b995f192e4b2e70b6112/app/state/actions/forms.js#L1-L41

Reasoning:
- Same reasoning for why it's a good idea to separate navigation from the store
- I don't see any benefit of putting it there
- Form states should be local to the component
- It will simplify the shape of the store

**Comment by imranariffin** [comment]
> * I don't see any benefit of putting it there

One benefit is we remove forms handling e.g validation & normalization out of components
> * Form states should be local to the component

I don't think this is necessarily true
> * It will simplify the shape of the store

Agree that it does simplify the state but that is not compelling to me

My take:
Agreed, remove from redux

Reasoning:
* Same reasoning for why it's a good idea to separate navigation from the store
* At this stage of the app, handling forms at redux level is perhaps too much work with minimal benefit
* At this stage of the app, handling forms at redux level is perhaps premature optimization - it  *could* help us handle forms validation & normalization in a more elegant way ... but this is thinking too far ahead.
