### ISSUE TITLE
authenticate & navigate on app startup

### ISSUE THREAD

**Issue by imranariffin** [hooligram/hooligram-client#50]
So far, every time the app starts up, it will go through onboarding. Once #47 is merged, we should work on enabling the app to:

1. authenticate on startup
2. decide based on authentication outcome whether to go through onboarding or navigate right away to global chat screen.

**Comment by cglotr** [comment]
Although #54 should fix this, let's keep this issue since I think we should have an initializing/loading splash screen of some sort as the initial route. That is to make it nicer.

**Comment by imranariffin** [comment]
Agreed
