### ISSUE TITLE
got can't find module from tests if using @hooligram/screens/...

### ISSUE THREAD

**Issue by cglotr** [hooligram/hooligram-client#61]
We need to figure out a better name for `package.json` files since `@hooligram/...` prefix will cause _can't find module name_ error from tests.

**Comment by imranariffin** [comment]
Interesting. We can either try to fix it from jest side or find a different way to rename it.

I tried using `module-alias` (https://www.npmjs.com/package/module-alias) but it didn't get it to work.

Maybe I'll try it again or try a different naming.

**Comment by cglotr** [comment]
> Interesting. We can either try to fix it from jest side or find a different way to rename it.
> 
> I tried using `module-alias` (https://www.npmjs.com/package/module-alias) but it didn't get it to work.
> 
> Maybe I'll try it again or try a different naming.

Related to this, I think I am now in favor for doing relative import for sibling files since absolute path can be quite long especially for components. Also, it gives us info that they are siblings. We should still avoid `..\xxx` tho

**Comment by imranariffin** [comment]
+1 for siblings
